**Why numpy?**

There are three main reasons for using numpy:

* Memory space: numpy arrays consume less space in memory.

* Runtime: If we compare with lists, it is much faster.

* Functionality: By using numpy, we are able to make vector operations with less coding. It is more effective to use than lists.

In [1]:
import numpy as np

In [2]:
il1 = np.tril_indices(4)
print(il1)

(array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3]), array([0, 0, 1, 0, 1, 2, 0, 1, 2, 3]))


**array**

In [3]:
l=[10, 8, 27, 9]
print(l, type(l))

[10, 8, 27, 9] <class 'list'>


In [4]:
arr=np.array(l)
print(arr)
print(type(arr))

[10  8 27  9]
<class 'numpy.ndarray'>


In [5]:
l1=[[27, 9], [10, 8]]
arr1=np.array(l1)

print(arr1)

[[27  9]
 [10  8]]


In [6]:
print(arr1.shape)

(2, 2)


In [7]:
print(arr1.size)

4


In [8]:
print(arr.dtype)

int32


In [9]:
data=np.arange(1, 10)

print(data)

[1 2 3 4 5 6 7 8 9]


In [10]:
data=np.arange(1, 10, 2)

print(data)

[1 3 5 7 9]


**random**

In [11]:
#uniform
print(np.random.rand(1))

[0.5847269]


In [12]:
print(np.random.rand(10))

[0.47336004 0.3159331  0.67131087 0.29505061 0.34282119 0.53952144
 0.95994203 0.42903855 0.71973123 0.36969955]


In [13]:
#mean=0, std=1
print(np.random.randn(3))

[ 0.24983718  0.18532479 -0.58090119]


In [14]:
#mean=2, std=2
print(np.random.normal(2, 2, 5))

[ 3.22872839  1.29729481 -1.18389957  1.71821498  3.61411769]


In [15]:
print(np.random.randint(1, 10))

6


In [16]:
print(np.random.randint(1, 10, 20))

[1 8 4 2 6 1 2 3 1 9 4 7 7 5 6 9 7 1 8 3]


In [17]:
#np.seed(54)

In [18]:
print(np.random.randint(1, 10))

1


In [19]:
data=np.arange(25)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [20]:
data.shape

(25,)

In [21]:
print(data.reshape(5, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [22]:
print(data.reshape(5, -1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**Indexing and selection**

In [23]:
data=np.array([[27, 9, 98], [10, 8, 98], [13, 6, 93], [1008, 2709, 1998]])
print(data)

[[  27    9   98]
 [  10    8   98]
 [  13    6   93]
 [1008 2709 1998]]


In [24]:
data[:, :]

array([[  27,    9,   98],
       [  10,    8,   98],
       [  13,    6,   93],
       [1008, 2709, 1998]])

In [25]:
data[:, 0]

array([  27,   10,   13, 1008])

In [26]:
data[:1, :]

array([[27,  9, 98]])

In [27]:
data[1:2, [0, 2]]

array([[10, 98]])

In [28]:
data[:2, 1:]

array([[ 9, 98],
       [ 8, 98]])

In [29]:
data>20

array([[ True, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [30]:
data[data>20]

array([  27,   98,   98,   93, 1008, 2709, 1998])

**copy**

In [31]:
arr1=np.random.randint(0, 25, 15)
print(arr1)

[ 1 23 13 13  1 10  4 18  3  4 23 24  4 16  8]


In [32]:
arr1[:6]

array([ 1, 23, 13, 13,  1, 10])

In [33]:
new=arr1[:6]
print(new)

[ 1 23 13 13  1 10]


In [34]:
new[:]=10
print(new)

[10 10 10 10 10 10]


In [35]:
print(new)
print(arr1)

[10 10 10 10 10 10]
[10 10 10 10 10 10  4 18  3  4 23 24  4 16  8]


In [36]:
arr1=np.random.randint(0, 25, 15)
print(arr1)

[22  3  7  9 12 22  7 18  5  2  6 22 16 20  1]


In [37]:
new_copy=arr1[:6].copy()
print(new_copy)

[22  3  7  9 12 22]


In [38]:
new_copy[:]=10
print(new_copy)

[10 10 10 10 10 10]


In [39]:
print(new_copy)
print(arr1)

[10 10 10 10 10 10]
[22  3  7  9 12 22  7 18  5  2  6 22 16 20  1]


**Math operations**

In [40]:
arr=np.array([10, 8, 27, 9])
print(arr)

[10  8 27  9]


In [41]:
arr+10

array([20, 18, 37, 19])

In [42]:
arr-8

array([ 2,  0, 19,  1])

In [43]:
arr/10

array([1. , 0.8, 2.7, 0.9])

In [44]:
arr+arr

array([20, 16, 54, 18])

In [45]:
arr-arr

array([0, 0, 0, 0])

In [46]:
arr/arr

array([1., 1., 1., 1.])

In [47]:
1/arr

array([0.1       , 0.125     , 0.03703704, 0.11111111])

In [48]:
np.sqrt(arr)

array([3.16227766, 2.82842712, 5.19615242, 3.        ])

In [49]:
np.sin(arr)

array([-0.54402111,  0.98935825,  0.95637593,  0.41211849])

In [50]:
np.log(arr)

array([2.30258509, 2.07944154, 3.29583687, 2.19722458])

In [51]:
print(arr)

[10  8 27  9]


In [52]:
print(arr.max())

27


In [53]:
print(arr.argmax())

2


In [54]:
print(arr.min())

8


In [55]:
print(arr.argmin())

1


In [56]:
print(data)

[[  27    9   98]
 [  10    8   98]
 [  13    6   93]
 [1008 2709 1998]]


In [57]:
print(data.sum())

6077


In [58]:
print(data.mean())

506.4166666666667


In [59]:
print(data.var())

774857.5763888889


In [60]:
print(data.std())

880.2599481908107


In [61]:
#column
print(data.sum(axis=0))

[1058 2732 2287]


In [62]:
#row
print(data.sum(axis=1))

[ 134  116  112 5715]


In [63]:
M=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* Two by matrix

In [64]:
T=np.random.randint(-2, 3, size=(2, 2))
print(T)

[[1 0]
 [2 1]]


**Particular Matrices**

* Identity matrix

In [65]:
I=np.eye(3, 4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


* Zeros matrix

In [66]:
Z=np.zeros((3, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* Ones matrix

In [67]:
O=np.ones((3, 4))
print(O)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


* Diagonal matrix

In [68]:
D=np.diag([8, 10, 27])
print(D)

[[ 8  0  0]
 [ 0 10  0]
 [ 0  0 27]]


In [69]:
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
D=np.diag(M)
print(D)

[1 5 9]


**Multiplying Matrices**

In [71]:
L=np.linspace(-8, 8, 9)
print(L)

[-8. -6. -4. -2.  0.  2.  4.  6.  8.]


In [72]:
M=L.reshape(3, 3)
print(M)

[[-8. -6. -4.]
 [-2.  0.  2.]
 [ 4.  6.  8.]]


In [73]:
N=np.random.randint(-8, 8, size=(3, 3))
print(N)

[[ 2 -6 -8]
 [-6  1 -2]
 [ 2 -7  6]]


In [74]:
np.matmul(M, N)

array([[ 12.,  70.,  52.],
       [  0.,  -2.,  28.],
       [-12., -74.,   4.]])

In [75]:
M.dot(N)

array([[ 12.,  70.,  52.],
       [  0.,  -2.,  28.],
       [-12., -74.,   4.]])

In [76]:
M@N

array([[ 12.,  70.,  52.],
       [  0.,  -2.,  28.],
       [-12., -74.,   4.]])

In [77]:
A=np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [78]:
B=np.array([[7, 2, -3], [0, 1, 6]])
print(B)

[[ 7  2 -3]
 [ 0  1  6]]


In [79]:
#A.dot(B)
A.dot(B.T)

array([[ 2, 20],
       [20, 41]])

**Calculating Matrix Determinant**

In [80]:
np.linalg.det(M)

0.0

In [81]:
np.linalg.det(N)

-528.0

**Perform More Operations with matrices**

In [82]:
np.linalg.inv(N)

array([[ 0.01515152, -0.17424242, -0.03787879],
       [-0.06060606, -0.0530303 , -0.09848485],
       [-0.07575758, -0.00378788,  0.06439394]])

In [83]:
M+N

array([[ -6., -12., -12.],
       [ -8.,   1.,   0.],
       [  6.,  -1.,  14.]])

In [84]:
M-N

array([[-10.,   0.,   4.],
       [  4.,  -1.,   4.],
       [  2.,  13.,   2.]])

In [85]:
2*M

array([[-16., -12.,  -8.],
       [ -4.,   0.,   4.],
       [  8.,  12.,  16.]])

**Given the following system of linear equation**

4*x+3*y+2*z=25            
-2*x+2*y+3*z=-10                  
3*x-5*y+2z=-4                  

In [86]:
M=np.array([
    [4, 3, 2],
    [-2, 2, 3],
    [3, -5, 2]
])

K=np.array([25, -10, -4])

**Solve linear equation using inverse method**

In [87]:
np.linalg.inv(M)

array([[ 0.15447154, -0.1300813 ,  0.04065041],
       [ 0.10569106,  0.01626016, -0.1300813 ],
       [ 0.03252033,  0.23577236,  0.11382114]])

In [88]:
print(np.linalg.inv(M).dot(K))

[ 5.  3. -2.]


In [89]:
print(np.linalg.solve(M, K))

[ 5.  3. -2.]


**NumPy exercises with Solutions**

##### 1. Create an array of 10 zeros 

In [90]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##### 2. Create an array of 10 ones

In [91]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


##### 3. Create an array of 10 fives

In [92]:
print(np.ones(10) * 5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


##### 4. Create an array of the integers from 10 to 50

In [93]:
print(np.arange(10,51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


##### 5. Create an array of all the even integers from 10 to 50

In [94]:
print(np.arange(10,51,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


##### 6. Create a 3x3 matrix with values ranging from 0 to 8

In [95]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


##### 7. Create a 3x3 identity matrix

In [96]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 8. Use NumPy to generate a random number between 0 and 1

In [97]:
print(np.random.rand(1))

[0.58803524]


##### 9. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [98]:
print(np.random.randn(25))

[ 0.05127451 -0.61884207  0.7320836  -0.12476619 -0.32646446 -0.04572478
 -1.0960337   0.72093775 -1.18122167 -1.1469036  -2.33535066 -0.70529665
 -0.20405907  0.1834426   0.1325453  -0.93263052 -0.68750684 -0.93165746
 -0.53371888  1.61918366 -1.24955048  0.02520698  2.10861868 -0.32505309
  0.5317562 ]


##### 10. Create the following matrix:

In [99]:
print(np.arange(1,101).reshape(10,10) / 100)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


##### 11. Create an array of 20 linearly spaced points between 0 and 1:

In [100]:
print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [101]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


##### 12. Get the sum of all the values in mat

In [102]:
print(mat.sum())

325


##### 13. Get the standard deviation of the values in mat

In [103]:
print(mat.std())

7.211102550927978


##### 14. Get the sum of all the columns in mat

In [104]:
print(mat.sum(axis=0))

[55 60 65 70 75]


##### 15. How to reshape an array?

In [105]:
arr = np.arange(10)

print(arr)

arr=arr.reshape(2,5)

print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


##### 16. How to stack two arrays vertically?

In [106]:
a = np.arange(10).reshape(2,-1)

print(a)

b = np.repeat(1, 10).reshape(2,-1)

print(b)

res=np.vstack([a,b])

print(res)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##### 17. How to stack two arrays horizontally?

In [107]:
a = np.arange(10).reshape(2,-1)

print(a)

b = np.repeat(1, 10).reshape(2,-1)

print(b)

print(np.hstack([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


##### 18. How to get the positions where elements of two arrays match?

In [108]:
a = np.array([12, 3, 27, 9, 97, 98, 10, 8])

b = np.array([12, 18, 28, 5, 3, 19, 10, 8])

print(np.where(a == b))

(array([0, 6, 7], dtype=int64),)


##### 19. Import the iris dataset keeping the text intact

In [109]:
iris_data=np.genfromtxt(r'datasets\Iris.csv',
                        delimiter=',', skip_header=1, dtype = object)

In [110]:
iris_data[:5, :]

array([[b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'3', b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4', b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5', b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']],
      dtype=object)

##### 20. Find the mean, median, standard deviation of iris's sepallength (1st column)

In [111]:
col_1=iris_data[:, 1].astype(float)

print(col_1[:5])

[5.1 4.9 4.7 4.6 5. ]


In [112]:
print('Mean', np.mean(col_1))
print('Median', np.median(col_1))
print('Standard Deviation', np.std(col_1))

Mean 5.843333333333334
Median 5.8
Standard Deviation 0.8253012917851409
